Fix tests for Windows EOL check
yegor256/qulice pull request #1236
Opened 2024-03-17 22:47 UTC by k3p7i3

Fixed tests for Windows EOL check. 
Also, refactored CheckstyleValidatorTest a little bit to make it more flexible for tests with their own licences.

Closes: #1127

2024-03-18 11:15 UTC, k3p7i3 commented
@yegor256 could you restart checks, please? it seems they weren't restarted after i added new commit.

2024-03-19 16:22 UTC, k3p7i3 commented
@yegor256 
This pull request doesn't pass checks because of the `testWindowsEndsOfLineWithLinuxSources` test.
The test is for the case when the license text is in `crlf` format, and the source code is in `lf` format, and the validation should fail.

When I run the test locally on Windows, it passes, but on Linux, it fails. In the screenshots, you can see that even the license text is parsed differently.
![Screenshot_20240319_184406](https://github.com/yegor256/qulice/assets/90573577/039a451c-e5a6-40c8-ab07-9dac5027a4fa)
![photo_2024-03-19_19-21-01](https://github.com/yegor256/qulice/assets/90573577/68dc30a8-dda2-4dda-bd9e-6db460b491d7)
In both cases, the license is created with `eol="\r\n"`, and the source code is in `lf` format, but on Linux, `HeaderCheck` from `checkstyle` does not see the difference.
Unfortunately, I have not been able to find a solution to this problem. Perhaps you know how this can be resolved?

2024-03-20 03:38 UTC, yegor256 commented
@pnatashap maybe you know how to help?

2024-03-20 03:49 UTC, pnatashap commented
@k3p7i3 @yegor256 the reason is by default files after checkout will have os-dependent end-of-line symbol (but stored as linux styled in git). So the best variant is to change symbol in case of non-windows os (tests are run on ubuntu and mac) before run validation (so we will check all variants).

also there is an option to enable test only for windows (@EnabledOnOs(WINDOWS))

2024-03-20 18:52 UTC, k3p7i3 commented
@pnatashap Thanks for the advice! I tried to change the end-of-line symbol, but it didn't work out for some reason (at least in my local linux environment). So I used the second option.

2024-03-20 18:54 UTC, k3p7i3 commented
@yegor256 please take a look

2024-03-21 00:44 UTC, pnatashap requested changes

2024-03-21 00:44 UTC, pnatashap commented on qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
> +            results,
please add reason for assertThat

2024-03-21 00:44 UTC, pnatashap commented on qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
> +                new ViolationMatcher(message, file, "3", name)
A can not match test name and validation in it: 
test is about windowEndsOfLine
validation is about HeaderCheck.

2024-03-21 00:44 UTC, pnatashap commented on qulice-checkstyle/src/test/java/com/qulice/checkstyle/CheckstyleValidatorTest.java
> +                    file, "1", "NewlineAtEndOfFileCheck"
It looks strange for me, that file has 10 lines of code and we are expecting NewlineAt**EndOfFile**Check at line 1

2024-05-16 13:11 UTC, yegor256 commented
@k3p7i3 what's up with this one? we continue?

2026-04-25 16:28 UTC, yegor256 commented
@k3p7i3 all tests are clean, I'm closing. thanks for your contribution anyway!

2026-04-25 16:28 UTC, closed without merging