[#1267] Add PMD tests that contains unicode characters in source code
yegor256/qulice pull request #1268
Opened 2024-05-08 13:54 UTC by c71n93

Related to #1267

2024-05-08 17:27 UTC, pnatashap requested changes

2024-05-08 17:27 UTC, pnatashap commented on qulice-pmd/src/test/java/com/qulice/pmd/PmdValidatorTest.java
> +    @Test
please add @DisabledOnOs(OS.Windows) for this test to be able to merge this PR

2024-05-08 17:59 UTC, c71n93 commented
@pnatashap done

2024-05-08 18:03 UTC, pnatashap commented
@yegor256 could you please merge this

2024-05-11 23:39 UTC, pnatashap commented
@c71n93 a get your tests with the fix. please, close this PR

2024-05-13 07:48 UTC, closed without merging